<?php

namespace AppBundle\Repository;

/**
 * staff4WLItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class staff4WLItemRepository extends \Doctrine\ORM\EntityRepository
{
}
