<?php

namespace AppBundle\Repository;

/**
 * workloadItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class workloadItemRepository extends \Doctrine\ORM\EntityRepository
{
}
